language: scala
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- sbt ++2.12.0-M4 ";compiler/publishLocal;library/publishLocal;javalibEx/publishLocal;testInterface/publishLocal;stubs/publishLocal;jasmineTestFramework/publishLocal;jUnitRuntime/publishLocal;jUnitPlugin/publishLocal"
# https://groups.google.com/d/msg/scala-internals/NZ4pVWB4HWY/CWtJJCqbHAAJ
